my bit of config - sel

diff --git a/_sel b/_sel
--- a/_sel
+++ b/_sel
@@ -1,7 +1,9 @@
+# my bit of config - sel
 _sel() {
- PS1='`jobs|tr -cd [`'$PS1
- alias s=git\ status py=python3
- export _SEL=_sel MANOPT=--nj\ --nh LESS=FR EDITOR=vim VIMINIT='sil! ru defaults.vim
+ [ -z ${PS1#?} ]&&PS1='\u@\h:\w\$ '
+ (command -v tr|:)&&PS1=${SHLVL%1}'`jobs|tr -cd [`'$PS1
+ alias l='command ls --color -FXx' ll=l\ -go py=python3 reset='stty sane -ixon' s=git\ status
+ export _SEL=_sel EDITOR=vim LESS=FR MANOPT=--nj\ --nh VIMINIT='sil! ru defaults.vim
   se hid isf-== ls=2 tm=0 noto ttimeout ttm=0 wmnu ai et sw=0 ts=4 nu rnu nowrap mouse=nv cul
   nn <C-N> :bn<CR>
   nn <C-P> :bp<CR>
@@ -11,6 +13,6 @@ _sel() {
   cno <C-F> <Right>
   cno <C-O> <C-F>
   cno <C-X> <C-A>'
- command_not_found_handle(){ echo "$0: $1: command not found">/dev/tty;stty sane -ixon 2>/dev/null;return 127;}
- bind -x'"\ez":fg&>/dev/null'
+ command_not_found_handle(){ echo "$0: $1: command not found">/dev/tty;reset;return 127;}
+ `command -v bind||echo :` -x'"\ez":fg&>/dev/null'
 }; [ _sel = "`command -v $_SEL`" ] && _sel
